// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMEqtdsXw7cGqatEKgXucWCUn5qTrYgRg',
    appId: '1:871415151741:web:7cce89fb58098050d08514',
    messagingSenderId: '871415151741',
    projectId: 'testcalidad-fe3e3',
    authDomain: 'testcalidad-fe3e3.firebaseapp.com',
    storageBucket: 'testcalidad-fe3e3.firebasestorage.app',
    measurementId: 'G-3L4MPXHSE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcd2T0nZ_2UVMkFGjOAOjlppWKn1npmKI',
    appId: '1:871415151741:android:e3705d8a440e0fb4d08514',
    messagingSenderId: '871415151741',
    projectId: 'testcalidad-fe3e3',
    storageBucket: 'testcalidad-fe3e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa4L6tezHNSBWME11ORjmIf16bHYXAxtw',
    appId: '1:871415151741:ios:1a48002ba121ee49d08514',
    messagingSenderId: '871415151741',
    projectId: 'testcalidad-fe3e3',
    storageBucket: 'testcalidad-fe3e3.firebasestorage.app',
    iosClientId: '871415151741-s2ck2p5co8hiv04vdl6c06np1jn9ah3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.surveys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa4L6tezHNSBWME11ORjmIf16bHYXAxtw',
    appId: '1:871415151741:ios:1a48002ba121ee49d08514',
    messagingSenderId: '871415151741',
    projectId: 'testcalidad-fe3e3',
    storageBucket: 'testcalidad-fe3e3.firebasestorage.app',
    iosClientId: '871415151741-s2ck2p5co8hiv04vdl6c06np1jn9ah3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.surveys',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMEqtdsXw7cGqatEKgXucWCUn5qTrYgRg',
    appId: '1:871415151741:web:da02b42232578eccd08514',
    messagingSenderId: '871415151741',
    projectId: 'testcalidad-fe3e3',
    authDomain: 'testcalidad-fe3e3.firebaseapp.com',
    storageBucket: 'testcalidad-fe3e3.firebasestorage.app',
    measurementId: 'G-YQ5EG5SQ1D',
  );
}
